inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

AllCops:
  NewCops: enable

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false